services:
  postgresql:
    image: sibedge/postgres-plv8
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - db_data:/data/postgres

  app:
    build:
      context: .
      dockerfile: images/app/Dockerfile
    depends_on:
      - postgresql
    ports:
      - "5000:5000"

volumes:
  db_data:
